
version: '3.3'
services:
  # from https://github.com/sikkimtemi/selenium
      
  # selenium
  selenium-hub:
    image: selenium/hub
    container_name: 'selenium-hub'
    ports:
      - 4444:4444

  # chrome headless
  chrome:
    image: selenium/node-chrome-debug
    container_name: 'chrome'
    ports:
      - 5900:5900
    volumes:
      - /dev/shm:/dev/shm
    privileged: true
    depends_on:
      - selenium-hub
    environment:
      - TZ=Asia/Tokyo
      - NODE_MAX_SESSION=1
      - no_proxy=localhost
      - HUB_ENV_no_proxy=localhost
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444

  #firefox:
  #  image: selenium/node-firefox-debug
  #  container_name: 'firefox'
  #  ports:
  #   - 5910:5900
  #  links:
  #    - selenium-hub:hub

  # source
  python:
    build: './'
    command: 'python ./startup.py'
    container_name: 'python'
    links:
      - selenium-hub:hub
    working_dir: '/root/script/'
    volumes:
      - ./tests/:/root/script/
    environment:
      - 'TZ=Asia/Tokyo'
